### ISSUE TITLE
Schema URI "schema-lax.json" could not be resolved

### ISSUE THREAD

**Issue by odan** [ergebnis/composer-normalize#417] opened 2020-04-30 22:11 UTC
#### Steps required to reproduce the problem

1. composer global update
2. composer normalize

#### Expected Result

* No error

#### Actual Result

`Schema URI "file://.../vendor/ergebnis/composer-normalize/resource/schema-lax.json" could not be resolved.`

**Comment by localheinz** [comment] 2020-05-01 09:30
@odan 

Cannot reproduce.

Running

```
$ rm -rf ~/.composer
$ composer global require ergebnis/composer-normalize:^2.5.0
$ git clone git@github.com:symfony/symfony.git
$ cd symfony
$ composer normalize
```

yields

```
Successfully normalized ./composer.json.
```

**Comment by odan** [comment] 2020-05-01 10:18
I tried to reinstall `ergebnis/composer-normalize` (v.2.5), but the error message remains. I will stay with v2.4 for now.

**Comment by localheinz** [comment] 2020-05-01 10:26
@odan 

Can you share the exact steps of what you are doing, so I can reproduce this issue?

**Comment by odan** [comment] 2020-05-01 10:29
I just updated from v.2.4 to v2.5

My commands:

* composer global update
* composer normalize

![image](https://user-images.githubusercontent.com/781074/80799663-bc1c6c00-8ba7-11ea-8655-616b3c799055.png)

The json file exists:

![image](https://user-images.githubusercontent.com/781074/80799734-ebcb7400-8ba7-11ea-97c7-755e9c546381.png)

**Comment by localheinz** [comment] 2020-05-01 10:52
@odan 

Thank you!

**Comment by localheinz** [comment] 2020-05-01 10:57
@odan 

Wondering, perhaps it is a problem with using `realpath()`. I haven't used Windows in years, so I have no idea.

Let's see if it fixes it for you.

**Comment by kubawerlos** [comment] 2020-05-01 10:58
@localheinz have you tried using `windows-latest` in Github Actions to reproduce it?

**Comment by localheinz** [comment] 2020-05-01 11:01
@kubawerlos 

I'll try - although that will add whole lot of additional builds.

Let's keep 🤞 that `composer/composer:^2` will be released soon - dropping support for `composer/composer:^1`, then!

**Comment by kubawerlos** [comment] 2020-05-01 11:06
I've done it this way: https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/v2.2.0/.github/workflows/ci.yml#L28 - to have only one Windows and macOS build each.

> Let's keep 🤞 that `composer/composer:^2` will be released soon - dropping support for `composer/composer:^1`, then!

It's still a lot here: https://github.com/composer/composer/milestone/23 :(

**Comment by localheinz** [comment] 2020-05-01 11:10
@kubawerlos 

Seeing what failed in #423, I think that Windows is a can of worms I am not going to open.

**Comment by localheinz** [comment] 2020-05-01 11:13
@odan 

Looking at https://github.com/ergebnis/composer-normalize/compare/2.4.0...2.5.0#diff-b972189fa805a313beac3d7eb57b8fc3, I do not understand why this should fail:

- using a `-` cannot be the problem
- perhaps referencing `schema.json` in `schema-lax.json` is a problem

**Comment by localheinz** [comment] 2020-05-01 11:39
@odan 

Can you try running

```
$ composer global require ergebnis/composer-normalize:dev-fix/schema
```

and then let me know if running

```
$ composer normalize
```

works for you?

**Comment by kubawerlos** [comment] 2020-05-01 11:45
@localheinz I have reproduced it on Windows (geez, it's slooow) and the fix from branch `fix/schema` solved the issue.

**Comment by localheinz** [comment] 2020-05-01 11:45
Thank you very much, @kubawerlos!

**Comment by odan** [comment] 2020-05-01 11:49
Now, the error is gone 👍 

![image](https://user-images.githubusercontent.com/781074/80803467-a496b080-8bb2-11ea-996d-52be738cb306.png)

**Comment by kubawerlos** [comment] 2020-05-01 11:51
I've tracked the issue to `JsonSchema\SchemaStorage::getSchema` method, Windows does not like/support/understand the `file://` prefix.

**Closed as completed** 2020-05-01 11:50 UTC

**Comment by localheinz** [comment] 2020-05-01 11:59
Thank you, @odan and @kubawerlos!

**Comment by odan** [comment] 2020-05-01 12:00
Thanks for fixing it so fast.
